### ISSUE TITLE
With current pytest version 3.2.2 pytest gives a test discovery error in VS code. This is solved by upgrading to version 3.5.0.

### ISSUE THREAD

**Issue by BrendBraeckmans** [MrPowers/quinn#107]
Hi,

In VS code the pytest discovery fails with the current pyproject.toml where the pytest version is set to 3.2.2 .
This is due to the fact that VS code makes use of the --rootdir option of pytest under the hood which is only supported from version 3.5.0 onwards as can be seen in the release notes [here](https://docs.pytest.org/en/7.1.x/changelog.html#pytest-3-5-0-2018-03-21).

Could we upgrade to version 3.5.0 to get this working ?

Best regards,
Brend

**Comment by SemyonSinchenko** [comment]
Done

**Comment by SemyonSinchenko** [comment]
Done.
