### ISSUE TITLE
[Feature Request] Accept  a csv of table metadata that returns a List of Struct Type Objects

### ISSUE THREAD

**Issue by sidharthbolar** [MrPowers/quinn#108]
Data in csv format is still ubiquitous
In case, I have several different types of csv 's 
The metadata about the csv can be provided externally

There is no in built method currently that allows me to intialize a StructType Object from csv file
Even though there is [fromJson](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.types.StructType.html#pyspark.sql.types.StructType.fromJson) method available

This will be a good helper method to avoid handcoding the schemas and to programatically create Structtype schemas for multiple table definitions from a  single csv file and to avoid using inferSchema as True

**Comment by jeffbrennan** [comment]
working on this

**Comment by MrPowers** [comment]
This has been added.
