### ISSUE TITLE
[Feature request]: Optimize all the delta tables in schema using a function.

### ISSUE THREAD

**Issue by puneetsharma04** [MrPowers/quinn#110]
Create a function that can take the name of specific tables as input or only the database name and optimize each & every table in the schema one by one. For Example:
"""
def optimize_delta_table(table_name):
    try:
        delta_table_metadata = spark.sql(f"DESCRIBE EXTENDED {table_name}").toPandas()
        delta_table_path = delta_table_metadata[delta_table_metadata["col_name"] == "Location"].iloc[0]["data_type"]
        spark.sql(f'OPTIMIZE delta.`{delta_table_path}`')

    except Exception as e:
        error_message = f" Error while optimising the delta table: {delta_table_path} : {e}"
        print(error_message)
        dbutils.notebook.exit(error_message)

"""

**Comment by robertkossendey** [comment]
@puneetsharma04 I think this feature should be rather part of [mack](https://github.com/MrPowers/mack) than quinn since this repository focuses on vanilla pyspark enhancements.

**Comment by MrPowers** [comment]
Yep, feel free to create an issue on the mack repo if you'd like to discuss this proposal in more detail with the mack community.
