### ISSUE TITLE
business_days_between fails on spark <= 3.0

### ISSUE THREAD

**Issue by SemyonSinchenko** [MrPowers/quinn#114]
@fpvmorais May you please have a look, why tests/test_functions.py::test_business_days_between fails on spark 3.0 and spark 2.4?

```sh
FAILED tests/test_functions.py::test_business_days_between - AttributeError: module 'pyspark.sql.functions' has no attribute 'transform'
```

I guess for spark of lover versions we should go a different way.
JFYI: We have an [extension](https://github.com/MrPowers/quinn/blob/main/quinn/extensions/dataframe_ext.py) specially for this task. You can use this trick or just rewrite the code a little

**Comment by SemyonSinchenko** [comment]
We are running our tests of 2.4.8, 3.0.3, 3.1.3, 3.2.4, 3.3.2 and 3.4.0; test fails on 2.4.8 and 3.0.3 only.

**Comment by MrPowers** [comment]
<img width="1013" alt="Screenshot 2023-09-25 at 4 06 48 PM" src="https://github.com/MrPowers/quinn/assets/2722395/70dcd4c7-7e11-4ac2-ac9f-0091fb5b5535">

I just noticed this as well.

I think there are still some users on Spark 2, so we should refactor the code.  At some point, we can drop Spark 2 support, but think we should keep supporting it for a while longer.

**Comment by MrPowers** [comment]
This is fixed now: https://github.com/MrPowers/quinn/pull/121
