### ISSUE TITLE
Run CI tests on branches as well

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#120]
We're only running the CI checks on the `main` branch right now.

It'd be helpful to run the CI checks on all branches, so it's easier to review PRs.  This will hopefully make it easier to avoid issues [like this one](https://github.com/MrPowers/quinn/issues/114).

**Comment by SemyonSinchenko** [comment]
If we use it by default `on: pull_request` we may start facing problems with the limit of GHA (3000 minutes/month as I remember). Maybe we should try to find a way to run it `on_dispatch` but with fork support? Because the problem with this PR was that I wasn't able to run action on fork and it's very hard to run tests on all versions locally (I only run on 3.3)...

**Comment by MrPowers** [comment]
@SemyonSinchenko - good point.  Would it be possible to run one set of CI tests (for a single Spark version) on the branches and the entire CI suite for all the Spark versions when merging with main?  You think that'd be a good compromise?

**Comment by SemyonSinchenko** [comment]
For me the perfect scenario will be to be able to run all spark tests manually on PR with a button. Looks like it is a tricky task but ChatGPT told me it is possible
![image](https://github.com/MrPowers/quinn/assets/29755009/415e92cb-5682-4af8-90f2-36576065400e)

**Comment by SemyonSinchenko** [comment]
So, we will have lightweight CI with linters that is triggered on every PR and also an option to run Unit tests on specific PR when we see it is necessary. Because linters requires 19 seconds but tests requires about 3 minutes and there is no reason to run it on PRs that, for example, change only a comma in docs

**Comment by SemyonSinchenko** [comment]
Another option is to set-up triggering only on a specific tag. So, for example, we can trigger tests only on PRs with tag `bug` or `feature` (or we can create our own tag like `tests-required`)

**Comment by SemyonSinchenko** [comment]
@MrPowers What do you think about all this options? Which one do you prefer?

**Comment by MrPowers** [comment]
@SemyonSinchenko - I like this suggestion: "So, we will have lightweight CI with linters that is triggered on every PR and also an option to run Unit tests on specific PR when we see it is necessary".  I suck at GitHub Actions, so hopefully we can provide some level of protection, but keep it simple.

Breaking main isn't great, but at least we have really solid checks setup now, so even if we break main, we can make sure to fix it before making a release.

**Comment by dinjazelena** [comment]
Hey, ideally, there should be template(very easy to set up) for each kind of issue (bug, feature, docs) and PR template.
Each issue is automatically labeled by its usecase(enhancement, docs, bug etc..) and also starts with given title like (DOCS: IssuenName, FEATURE:IssueName, BUG:IssueName).
It gives u much more transparency and readability especially for people wanting to contribute.

And then u could trigger your CI workflows based on given label. So for new feature request and bugs ofcourse u want to run your spark versions etc..
For docs or something similar, not really.
You can assign this to me if u wish.

**Comment by MrPowers** [comment]
Thanks for offering to help @dinjazelena.  Let us know if you need any help.

**Comment by SemyonSinchenko** [comment]
Close this one for #203

Bceuase #203 is about some kind of a simple solution, this one may be reopened at any moment.
