### ISSUE TITLE
Use quinn.create_df() to fix deprecation warnings

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#122]
Here are the deprecation warnings:

```
tests/test_dataframe_validator.py::describe_validate_schema::it_raises_when_struct_field_is_missing1
  /Users/matthew.powers/Documents/code/my_apps/quinn/tests/test_dataframe_validator.py:40: PendingDeprecationWarning: Function 'semver.compare' is deprecated. Deprecated since version 3.0.0.  Still under investigation, see #258. Use the respective 'semver.Version.compare' instead.
    if semver.compare(spark.version, "3.3.0") >= 0:  # Spark 3.3+

tests/test_functions.py::test_single_space
  /Users/matthew.powers/Documents/code/my_apps/quinn/tests/test_functions.py:26: DeprecationWarning: Extensions may be removed in the future versions of quinn. Please use `quinn.create_df()` instead
    df = spark.create_df(
```

We need to switch to `quinn.create_df()`.

We also need to switch from `semver.compare` to `semver.Version.compare`.  Yep, the tool we're using to send deprecation warnings is also sending us a deprecation warning.  We're in deprecation warning inception.  Ah, the joys of software development.

**Comment by jeffbrennan** [comment]
@MrPowers can this be closed? Looks like test_single_space() uses `quinn.create_df()` and `describe_validate_schema()` uses `semver.Version.compare` now.

**Comment by MrPowers** [comment]
Yep, this is done, thanks for the ping @jeffbrennan
