### ISSUE TITLE
Fix CI lint checks

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#134]
Fix all the CI lint checks (perhaps running black code formatting will fix some of them).

Ignore all the Python code in the `tests/` directory, so we don't have to make all these changes:

<img width="909" alt="Screen Shot 2023-10-04 at 10 03 57 PM" src="https://github.com/MrPowers/quinn/assets/2722395/12408a61-3001-4da6-8af8-e0c9aa29adf5">

**Comment by dinjazelena** [comment]
@MrPowers , hey, u merged my previous PR, but i did not finish it actually. My mistake, should have put PR in draft.
So will open new PR to finish CI and linting with ruff and mypy.
Black requires at least python3.8.
