### ISSUE TITLE
Document with_columns_renamed in the README

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#137]
`with_columns_renamed` is a cool function that should definitely be documented.

**Comment by itsgalarza** [comment]
I'm interested in this one! 🧑‍💻

**Comment by MrPowers** [comment]
@itsgalarza - let us know when you've made a PR!

**Comment by kunaljubce** [comment]
@MrPowers @SemyonSinchenko I can take this up.

**Comment by SemyonSinchenko** [comment]
@MrPowers may we assign @kunaljubce to this?

**Comment by MrPowers** [comment]
Yep, @kunaljubce assigned this one to you!
