### ISSUE TITLE
Add material for mkdocs

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#162]
[Material is a cool plugin](https://squidfunk.github.io/mkdocs-material/) that makes mkdocs generated doc sites look beautiful.

I think we should add material to the quinn docs and make them awesome!

**Comment by dinjazelena** [comment]
Can u assign me on this one, i am interested in documentation?

**Comment by MrPowers** [comment]
@dinjazelena - sure, assigned this to you!

**Comment by MrPowers** [comment]
I chatted with @jeffbrennan and he volunteered to grab this one!
