### ISSUE TITLE
Add ruff format for auto formation of code

### ISSUE THREAD

**Issue by dinjazelena** [MrPowers/quinn#163]
Hey, what do u think about adding ruff format: https://docs.astral.sh/ruff/formatter/ as substition for Black. So all in one for linting and code quality.

**Comment by MrPowers** [comment]
Yea, this look good to me.  Thoughts @SemyonSinchenko @jeffbrennan?

**Comment by dinjazelena** [comment]
@MrPowers @SemyonSinchenko , should i proceed with this one?

**Comment by SemyonSinchenko** [comment]
I'm OK with it. But we need to update the CONTRIBUTING about how to add ruff into IDEs.

**Comment by nijanthanvijayakumar** [comment]
> I'm OK with it. But we need to update the CONTRIBUTING about how to add ruff into IDEs.

@SemyonSinchenko - shall I update the `CONTRIBUTING.md` file to describe how to add ruff into IDEs like VSCode and PyCharm?
