### ISSUE TITLE
Add maintainers to pyproject.toml

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#173]
Example: https://github.com/python-poetry/poetry/blob/master/pyproject.toml#L6-L14

**Comment by SemyonSinchenko** [comment]
What about the creation of the mailing list, too? Like for updates, announcements about contribution meetings, etc.?

**Comment by MrPowers** [comment]
@SemyonSinchenko - that's a good idea too 💡  I created another issue to track the creation of a mailing list.

**Comment by vedanthv** [comment]
I would like to take this up @MrPowers. Its my first issue here, would require some help!

**Comment by nijanthanvijayakumar** [comment]
take
