### ISSUE TITLE
0.10.1 and 0.10.2 have changed import method of array_choice from 0.10.0

### ISSUE THREAD

**Issue by AmberGibney** [MrPowers/quinn#197]
In 0.10.0 you could, as per many other functions, call quinn.array_choice(), now as it is not in the __init__.py, it has to be imported from quinn.functions. 

Is this intentional behaviour? It seems like a pretty large change from 0.10.0 to 0.10.1.

**Comment by SemyonSinchenko** [comment]
@MrPowers I 100% agree. As I mentioned already, if your goal is to make quinn works with SparkConnect, I suggest to do it in a new major release.

**Comment by MrPowers** [comment]
Turns out that this one slipped through the cracks because the `array_choice` test was commented out.  I commented that out cause I wasn't able to make the test deterministic on localhost/CI.

**Comment by MrPowers** [comment]
<img width="624" alt="Screenshot 2024-02-13 at 7 46 07 AM" src="https://github.com/MrPowers/quinn/assets/2722395/5afb9633-6789-4cec-9817-426d15a1318d">

@AmberGibney - this should be fixed with quinn v0.10.3
