### ISSUE TITLE
Integrate Quinn with Travis

### ISSUE THREAD

**Issue by afranzi** [MrPowers/quinn#20]
@MrPowers what do you think about integrating Quinn with Travis to run tests and to publish automatically to Pypi?

**Comment by MrPowers** [comment]
@afranzi - Added Travis.  Build isn't working yet... ironically because of the SparkSession stuff that we're working on in the other PR.

Let's get the build passing and then talk about automatically publishing to PyPi... that could be really cool.

**Comment by afranzi** [comment]
Cool, Travis integration solved in #19
