### ISSUE TITLE
Create a GitHub action to auto-assign issues

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#204]
Create a GitHub action that auto-assigns issues to users when they submit a comment that's equal to "take".

See here for an example: https://github.com/delta-io/delta-rs/issues/2203

**Comment by SemyonSinchenko** [comment]
@MrPowers It doesn't look very hard, especially due to provided example. May I add a tag `good-first-issue`?

**Comment by paulooctavio** [comment]
@MrPowers Can I take this one?
