### ISSUE TITLE
Add Apache-2.0 LICENSE, license-header to all the files and incorporate license-header checks

### ISSUE THREAD

**Issue by SemyonSinchenko** [MrPowers/quinn#207]
The quinn repository is distributed under Apache 2.0 LICENSE, but is mentioned in [non-standard place](https://github.com/MrPowers/quinn/blob/main/pyproject.toml#L6).

My suggestion is to do the following:
1. Add LICENSE file with text of Apache 2.0 license
2. Add license header to all the files of `quinn` except `poetry.lock` (or other auto-generated stuff)
3. Create `.licenserc` file (
4. Incorporate [skywalking-eyes](https://github.com/apache/skywalking-eyes) into quinn CI

Hints:
1. [An example of configuration of skywalker-eye](https://github.com/apache/skywalking-eyes?tab=readme-ov-file#configurations)
2. [An example of CI-usage of skywalker-eye](https://github.com/apache/skywalking-eyes?tab=readme-ov-file#check-license-headers)
3. [An example of LICENSE file for Apache 2.0](https://github.com/apache/spark/blob/master/LICENSE)
4. [An example of Apache-2.0 license header in python file](https://github.com/apache/spark/blob/master/python/pyspark/__init__.py#L1)

**Comment by MrPowers** [comment]
Issue looks good to me!

**Comment by squerez** [comment]
Can I tackle this one?

**Comment by nijanthanvijayakumar** [comment]
take

**Comment by nijanthanvijayakumar** [comment]
Hi there @SemyonSinchenko - I have created the PR, as linked above for this issue. Please let me know if the changes look good. 

**_PS:_** this is my first time creating an OSS PR; keen to hear any comments re: room for improvements. 😄
