### ISSUE TITLE
Update surround_substring to surround all substrings

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#209]
It works properly when there is only one substring like here: `surround_substring("spark rdd stuff", "rdd", "**", "||")`.

It does not work properly when there are two substrings, like here: `surround_substring("spark rdd stuff with rdd", "rdd", "**", "||")`.

<img width="414" alt="Screenshot 2024-02-23 at 10 54 28 AM" src="https://github.com/MrPowers/quinn/assets/2722395/504c2314-380f-485b-b074-a559b10e772d">

**Comment by SemyonSinchenko** [comment]
@MrPowers What do you think about the case when we want to branch depending on SparkConnect? For example:

```python
if hasattr(spark, "_jvm"):
    spark_code(...)
else:
    spark_connect_code(...)
```

**Comment by MrPowers** [comment]
@SemyonSinchenko - the purpose of this code is to run on other libraries and identify any files that contain potentially problematic code.

I am considering creating a separate project with the intention of making Spark Connect less breaking.  That library would use the design pattern you outlined above.  It would be great if we could monkey patch in the "old way" and just do the new "Spark Connect way" under the hood (when possible of course).
