### ISSUE TITLE
DOC: Structural inconsistency of quinn examples in the README documentation 

### ISSUE THREAD

**Issue by kunaljubce** [MrPowers/quinn#213]
### Quinn version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://mrpowers.github.io/quinn/)

### Location of the documentation

README.md file

### Documentation problem

We have a structural inconsistency in the quinn README examples. In some examples, it is of the format:
```
Function Name 
     |
Example
     |
Description
```

And in some other examples, the format is:
```
Function Name 
     |
Description
     |
Example
```
![image (1)](https://github.com/MrPowers/quinn/assets/34453918/c4e61ac3-d720-439e-a065-db0b4d66a7ed)

### Suggested fix for documentation

From a new user point of view, the latter seems easier to follow, i.e. 
```
Function Name 
     |
Description
     |
Example
```

Please create a PR to change all examples on `README.md` to fit this format.

**Comment by SemyonSinchenko** [comment]
@kunaljubce May I assign it to you?
