### ISSUE TITLE
DOC: Typo in the Contributions doc

### ISSUE THREAD

**Issue by vedanthv** [MrPowers/quinn#223]
### Quinn version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://mrpowers.github.io/quinn/)

### Location of the documentation

[contribution guidelines](https://github.com/MrPowers/quinn/blob/main/CONTRIBUTING.md)

### Documentation problem

Found a typo, the heading should be "Running Tests" instead of "Rinning Tests"

![image](https://github.com/MrPowers/quinn/assets/44313631/e6f22163-52c2-426b-b0de-6f7d21024759)

### Suggested fix for documentation

Easy fix by correcting the spelling to "Running"

**Comment by MrPowers** [comment]
Looks good, can you please submit a PR?

**Comment by vedanthv** [comment]
Sure will do that
