### ISSUE TITLE
feat: Drop extension fuinctions

### ISSUE THREAD

**Issue by SemyonSinchenko** [MrPowers/quinn#237]
### Feature Type

- [ ] Adding new functionality to quinn

- [ ] Changing existing functionality in quinn

- [ ] Removing existing functionality in quinn

### Problem Description

Extension functions are deprecated for a long time, we should drop them from 1.0

### Feature Description

Drop them:
- https://github.com/MrPowers/quinn/blob/main/quinn/extensions/dataframe_ext.py
- https://github.com/MrPowers/quinn/blob/main/quinn/extensions/spark_session_ext.py#L48

**Comment by nijanthanvijayakumar** [comment]
@SemyonSinchenko - can I take this up please?
