### ISSUE TITLE
DOC: Update README.md with correct function names

### ISSUE THREAD

**Issue by nijanthanvijayakumar** [MrPowers/quinn#238]
### Quinn version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://mrpowers.github.io/quinn/)

### Location of the documentation

[README.md](https://github.com/MrPowers/quinn/blob/main/README.md)

### Documentation problem

The [README.md file's `Column Extensions`](https://github.com/MrPowers/quinn/blob/main/README.md?plain=1#L477-L517) section contains functions such as `nullBetween`, `isFalsy` etc., that have a different name in the [`functions.py`](https://github.com/MrPowers/quinn/blob/main/quinn/functions.py#L305-L392) file.

### Suggested fix for documentation

Update the README.md file to reflect the correct function name and their description (matching with the doc-string).

**Comment by fatemetardasti96** [comment]
I would like to work on this issue as my first contribution

**Comment by fatemetardasti96** [comment]
here is the PR: https://github.com/MrPowers/quinn/pull/240
