### ISSUE TITLE
feat: Add spark-connect tests suite and run existing tests with SC

### ISSUE THREAD

**Issue by SemyonSinchenko** [MrPowers/quinn#241]
### Feature Type

- [X] Adding new functionality to quinn

- [ ] Changing existing functionality in quinn

- [ ] Removing existing functionality in quinn

### Problem Description

We need to test quinn against both connect and classic.

### Feature Description

.

### Additional Context

This one may be used as an example: https://github.com/pyspark-ai/pyspark-ai/blob/master/run_spark_connect.sh

**Comment by nijanthanvijayakumar** [comment]
Hi @SemyonSinchenko - are you okay if I give this one a try?

**Comment by SemyonSinchenko** [comment]
@nijanthanvijayakumar This one is little tricky. It requires to download and run Spark-Connect server before running tests and also use `SparkSession.remote(...)`. You may check how I did it for pyspark-ai:
1. https://github.com/pyspark-ai/pyspark-ai/blob/master/run_spark_connect.sh
2. https://github.com/pyspark-ai/pyspark-ai/blob/master/.github/workflows/build_and_test.yml#L33
3. https://github.com/pyspark-ai/pyspark-ai/blob/master/tests/test_spark_connect.py

**Comment by SemyonSinchenko** [comment]
Feel free to ask me if you face any problem with it.

**Comment by nijanthanvijayakumar** [comment]
> Feel free to ask me if you face any problem with it.

Thank you; will definitely do. A few initial questions:

1. Does the version have to be locked to v3.5.1?
2. Also does all of the functions have to be tested with Spark-Connect?

**Comment by SemyonSinchenko** [comment]
> > Feel free to ask me if you face any problem with it.
> 
> Thank you; will definitely do. A few initial questions:
> 
> 1. Does the version have to be locked to v3.5.1?
> 2. Also does all of the functions have to be tested with Spark-Connect?

1. I would like to take a version from environment variable
2. We do need to cover all the cases but it could be cool to cover each function at least once

BUT! To avoid very big PRs that are hard to review, please focus at first on CI/CD and suite. You may create a single test for that.

**Comment by nijanthanvijayakumar** [comment]
@SemyonSinchenko - I created the basic version based on the references you shared and I got a pretty good idea of what all files should be changed to extend the Spark-Connect session to the other tests. [Here's the link to the commit](https://github.com/nijanthanvijayakumar/quinn/commit/a4457ec97b15fb8b376afff4f99d335cab8ceae1).

However, I was trying to execute the spark-connect tests using `make` on my local and it has been failing with issues related to dependencies such as `pandas`, `numpy` and `pyarrow`. Following are the versions of those libraries/dependencies I updated in the `pyproject.toml` and tried setting them up in my local VENV. 

```toml
[tool.poetry.dependencies]
pandas = "^1.3.0"
pyarrow = "^5.0.0"
numpy = "^1.21.0"
```


However, while installing `pyarrow` I keep getting an error (as below). Have you faced that while setting this up for `pyspark.ai`? **Any suggestions on how to resolve these issues?**

```bash
Note: This error originates from the build backend, and is likely not a problem with poetry but with numpy (1.19.4) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "numpy (==1.19.4)"'.
  
  Error:
 
  at /opt/homebrew/Cellar/poetry/1.8.3_2/libexec/lib/python3.12/site-packages/poetry/installation/chef.py:102 in install
       98│             InstalledRepository.load(self._env),
       99│         )
      100│         installer.update(True)
      101│         if installer.run() != 0:
    → 102│             raise ChefInstallError(requirements, io.fetch_output(), io.fetch_error())
      103│ 
      104│ 
      105│ class Chef:
      106│     def __init__(

Cannot install build-system.requires for pyarrow.
```

**Comment by nijanthanvijayakumar** [comment]
> @SemyonSinchenko - I created the basic version based on the references you shared and I got a pretty good idea of what all files should be changed to extend the Spark-Connect session to the other tests. [Here's the link to the commit](https://github.com/nijanthanvijayakumar/quinn/commit/a4457ec97b15fb8b376afff4f99d335cab8ceae1).
> 
> However, I was trying to execute the spark-connect tests using `make` on my local and it has been failing with issues related to dependencies such as `pandas`, `numpy` and `pyarrow`. Following are the versions of those libraries/dependencies I updated in the `pyproject.toml` and tried setting them up in my local VENV.
> 
> ```toml
> [tool.poetry.dependencies]
> pandas = "^1.3.0"
> pyarrow = "^5.0.0"
> numpy = "^1.21.0"
> ```
> 
> Tried with `pyarrow=4.0.1` and `numpy=2.0.0` as well. Observing the same issue.
> 
> However, while installing `pyarrow` I keep getting an error (as below). Have you faced that while setting this up for `pyspark.ai`? **Any suggestions on how to resolve these issues?**
> 
> ```shell
> Note: This error originates from the build backend, and is likely not a problem with poetry but with numpy (1.19.4) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "numpy (==1.19.4)"'.
>   
>   Error:
>  
>   at /opt/homebrew/Cellar/poetry/1.8.3_2/libexec/lib/python3.12/site-packages/poetry/installation/chef.py:102 in install
>        98│             InstalledRepository.load(self._env),
>        99│         )
>       100│         installer.update(True)
>       101│         if installer.run() != 0:
>     → 102│             raise ChefInstallError(requirements, io.fetch_output(), io.fetch_error())
>       103│ 
>       104│ 
>       105│ class Chef:
>       106│     def __init__(
> 
> Cannot install build-system.requires for pyarrow.
> ```

@SemyonSinchenko - an update on the above.

1. I was able to fix that by using `pyarrow=1.16.x`. I have updated the `pyproject.toml` with the latest list of libraries.
2. I was able to get this spark-connect test working in CI 🥳. [Here's the link to the GitHub Actions on my fork](https://github.com/nijanthanvijayakumar/quinn/actions/runs/9932617910/job/27434196153).

I will raise a PR for you to review. Please let me know your comments on that.

**Comment by SemyonSinchenko** [comment]
@nijanthanvijayakumar I think you may continue to work in this issue. If you can, try to run all the existing tests with Spark Connect. Feel free to ask me, if you face any issue.

**Comment by nijanthanvijayakumar** [comment]
Thank you @SemyonSinchenko . Will work on integrating the test cases and create a new PR.

**Comment by nijanthanvijayakumar** [comment]
@SemyonSinchenko - sorry I have been away from my computer for a while. I was able to fix the `column_to_list` function under the `quinn/dataframe_helpers.py`, which was one of the tests that were failing.

However, there are a couple of other test cases/functions that were failing too. Following are those:
- test_array_choice
- test_sort_struct_nested_with_arraytypes_nullable

```bash
| =========================== short test summary info ============================
| FAILED tests/test_functions.py::test_array_choice - TypeError: Unsupported Data Type Column
| FAILED tests/test_transformations.py::test_sort_struct_nested_with_arraytypes_nullable - chispa.schema_comparer.SchemasNotEqualError: 
```

**Comment by SemyonSinchenko** [comment]
@nijanthanvijayakumar Thank you! May you post a more detailed stacktrace? Or even run tests in CI in your fork an give me a link to the logs?

**Comment by nijanthanvijayakumar** [comment]
Thank you. Yep, here they are:
1. [CI pipeline for Spark-Connect 3.4.3 tests](https://github.com/nijanthanvijayakumar/quinn/actions/runs/10234737769/job/28314602319#step:10:36)
2. [CI pipeline for Spark-Connect 3.5.1 tests](https://github.com/nijanthanvijayakumar/quinn/actions/runs/10234737769/job/28314602384#step:10:36)

**Comment by SemyonSinchenko** [comment]
@nijanthanvijayakumar It seems to me that you found an interesting behavior. Let's pause it for now.

**Comment by nijanthanvijayakumar** [comment]
Thank you @SemyonSinchenko; tried fixing this for hours and couldn't. Keen to know/learn more about the behaviour here.

**Comment by SemyonSinchenko** [comment]
It seems to me that is a bug in PySpark itself.
@nijanthanvijayakumar Are you in 'mrpowers' slack channel, related to this project? If so, may you say ur nickname

**Comment by nijanthanvijayakumar** [comment]
> It seems to me that is a bug in PySpark itself.
> 
> @nijanthanvijayakumar Are you in 'mrpowers' slack channel, related to this project? If so, may you say ur nickname

@SemyonSinchenko - I'm not in that channel, but would love to be part of it. Thanks.

**Comment by SemyonSinchenko** [comment]
@nijanthanvijayakumar Give me your email, please. I will ask @MrPowers to contact you

**Comment by nijanthanvijayakumar** [comment]
Hi @SemyonSinchenko - thanks. It's nijanthanvijayakumar@outlook.com

**Comment by nijanthanvijayakumar** [comment]
Hello @SemyonSinchenko . Hope you got my email address (noticed your thumbs up earlier and I assumed you had got it)? I have removed it from this chat for now, just for privacy reasons.

**Comment by SemyonSinchenko** [comment]
@nijanthanvijayakumar FYI https://github.com/apache/spark/commit/536445cc9544e22ca8b988684c0bb3df4bbed77e

May you mark this function as "non-working" if the version of spark is less than 4.0 (or less than 3.5.2 for 3.5-branch) and throw an exception, like "This function is not working in Connect environments for spark less than 3.5.2"?

**Comment by nijanthanvijayakumar** [comment]
> @nijanthanvijayakumar FYI [apache/spark@536445c](https://github.com/apache/spark/commit/536445cc9544e22ca8b988684c0bb3df4bbed77e)
> 
> May you mark this function as "non-working" if the version of spark is less than 4.0 (or less than 3.5.2 for 3.5-branch) and throw an exception, like "This function is not working in Connect environments for spark less than 3.5.2"?

Hi @SemyonSinchenko - if my understanding is right, do you want me to do the following?
1. [In the link you had shared](https://github.com/apache/spark/commit/536445cc9544e22ca8b988684c0bb3df4bbed77e), comment _This function is not working for Spark-Connect v3.5.2 and less_ and,
2. Update the `test_array_choice` and `test_sort_struct_nested_with_arraytypes_nullable` test cases to throw an exception saying `This function is not working on Spark-Connect environments for Spark version less than 3.5.2`?

**Comment by SemyonSinchenko** [comment]
I mean you should mark functions in chispa as non-workin in connect. These functions (array_choice, etc.) should trow an exception if u are trying to call them in Connect env from spark version less than 3.5.2

**Comment by nijanthanvijayakumar** [comment]
> @nijanthanvijayakumar FYI [apache/spark@536445c](https://github.com/apache/spark/commit/536445cc9544e22ca8b988684c0bb3df4bbed77e)
> 
> May you mark this function as "non-working" if the version of spark is less than 4.0 (or less than 3.5.2 for 3.5-branch) and throw an exception, like "This function is not working in Connect environments for spark less than 3.5.2"?

Thanks for the guidance @SemyonSinchenko . I have updated the test cases and the actual function implementation accordingly. I will be sending a PR shortly.
