### ISSUE TITLE
Move Spark session code outside of this repo

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#36]
There's a class that creates a SparkSession that's used by the test suite: https://github.com/MrPowers/quinn/blob/master/quinn/spark.py

The quinn methods [don't depend on this SparkSession](https://github.com/MrPowers/quinn/blob/master/quinn/dataframe_helpers.py#L29-L38), which is good.  We want quinn to be easily runnable on all different types of platforms and we generally want the execution platform to define the SparkSession, not quinn.

It's probably best to simply move this class to the `tests/` directory.  That way we can still access it and use it as a good example for the community, but it'll be clear that we shouldn't use it for code in the `quinn/` directory.  

It might be cool to monkey patch a `transform` method on the SparkSession class so it's easier to write code that leverages the existing SparkSession without creating a new one (or running getOrCreate).  Passing the spark session as an argument and solving the problem with dependency injection is always an option, but if we go this route, we should make conventions, like always having the spark session as the first argument when it's injected.

**Comment by sidharthbolar** [comment]
Is this issue still open for contributions?
