### ISSUE TITLE
Deprecation warning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [MrPowers/quinn#39]
Deprecation warnings are raised due to invalid escape sequences. This can be fixed by using raw strings or escaping the literals. pyupgrade also helps in automatic conversion : https://github.com/asottile/pyupgrade/

```
find . -iname '*.py' | grep -Ev 'vendor|example|doc|tools|sphinx' | xargs -P4 -I{} python3.8 -Wall -m py_compile {}
./quinn/scala_to_pyspark.py:49: DeprecationWarning: invalid escape sequence \s
  m = re.search('(\s*)def (\w+).*\((.*)\)', s)
```

**Comment by MrPowers** [comment]
@tirkarthi - thanks for creating this issue.  Definitely don't want to have any code that outputs deprecation warnings.  Think this should fix it: https://github.com/MrPowers/quinn/pull/40/files. Does fix look good to you?

**Comment by MrPowers** [comment]
The deprecation warning has been fixed: https://github.com/MrPowers/quinn/pull/40

**Comment by tirkarthi** [comment]
Thanks, unrelated to the issue I just left a comment on parsing function definition to see if the regex is lenient : https://github.com/MrPowers/quinn/pull/40#discussion_r462420234
