### ISSUE TITLE
Ignore nullable for validate_schema

### ISSUE THREAD

**Issue by cosmincatalin** [MrPowers/quinn#43]
Are you open to a PR for adding an option to `validate_schema` so as to ignore the `nullable` property?

**Comment by MrPowers** [comment]
@cosmincatalin - Yep, sounds like a good addition, please feel free to send a pull request.  Thanks for opening this issue.

**Comment by cosmincatalin** [comment]
We have opened PR #44

**Comment by MrPowers** [comment]
Next steps: review the PR, make sure it can get merged and will be 100% backwards compatible, merge it, let all interested stakeholders know, and apologize profusely for taking so long.

**Comment by cosmincatalin** [comment]
How's the review going, @MrPowers ? We're anxiously waiting to get rid of our custom code and replace it with quinn alone.

**Comment by robertkossendey** [comment]
@MrPowers I think we can merge this PR :)

**Comment by MrPowers** [comment]
@cosmincatalin - this was merged, sorry for the delay.
