### ISSUE TITLE
Make create_df better

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#46]
quinn lets you do this right now:

```python
spark.create_df(
    [("jose", "a"), ("li", "b"), ("sam", "c")],
    [("name", StringType(), True), ("blah", StringType(), True)]
)
```

It'd also be cool if this was possible:

```python
spark.create_df(
    [("jose", "a"), ("li", "b"), ("sam", "c")],
    ["name", "blah"]
)
```

**Comment by MrPowers** [comment]
@arthurnw - have at it ;)

**Comment by sidharth1805** [comment]
@MrPowers I am interested to contribute to this and need some help to get started.

**Comment by MrPowers** [comment]
@sidharth1805 - thanks for the ping.  I actually though about this one more and this function isn't necessary because it's the same as the built-in createDataFrame functionality, haha.  I will try to ping you on another issue that'd be better to grab!

**Comment by sidharth1805** [comment]
Sure @MrPowers happy to contribute
