### ISSUE TITLE
Add a flatten DataFrame method

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#47]
This was suggested as an addition to chispa here: https://github.com/MrPowers/chispa/issues/47

I think this would be an even better addition to quinn because it's also useful for general data engineering (not just testing).

This function would help a lot of users.

**Comment by bjornjorgensen** [comment]
I have [a JIRA](https://issues.apache.org/jira/projects/SPARK/issues/SPARK-36950) for this.

**Comment by MrPowers** [comment]
@bjornjorgensen - the JIRA link isn't loading for me.  Do you want to [open up a PR with this code](https://github.com/MrPowers/chispa/issues/47)?  Looks like you've already done the legwork for this one.

**Comment by kv41999** [comment]
Hi @MrPowers, I have a custom function that flattens the spark df, array and struct columns included. I you like I would love to contribute.  Just let me know which file the changes need to be made to. 
Thanks
