### ISSUE TITLE
Make sure column_to_list method is as performant as possible

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#53]
This blog post summarizes the most performant ways to convert a PySpark DataFrame column into a list: https://mungingdata.com/pyspark/column-to-list-collect-tolocaliterator/

We should update the benchmarking for the latest version of Spark and then make sure quinn is using the most performant implementation.

**Comment by SemyonSinchenko** [comment]
Which version of Spark is most important? Cause I guess that result will be different for different versions. Also for `toPandas` I guess that results will be significantly different with `spark.sql.execution.arrow.enabled` and without it... Should we also check performance of Java-ways (via collecting data with `py4j`) or readability of code is the most important thing and we should avoid of using unreadable `py4j` calls?

**Comment by MrPowers** [comment]
This is done, thanks @jeffbrennan
