### ISSUE TITLE
Add flake8

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#58]
See mack for an example of a PySpark project with flake8: https://github.com/MrPowers/mack

**Comment by squerez** [comment]
Tackled in https://github.com/MrPowers/quinn/pull/66

**Comment by SemyonSinchenko** [comment]
@MrPowers Why you do not want to use `Ruff` instead of `flake8`? It is more modern way with the same functionality...
https://beta.ruff.rs/docs/

**Comment by MrPowers** [comment]
@SemyonSinchenko - opened up a separate issue to explore the possibility of using Ruff with the community.
