### ISSUE TITLE
Refactor the DataFrame#transform method to be more elegant

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#6]
This library defines a `DataFrame.transform` method to chain DataFrame transformations as follows:

```python
from pyspark.sql.functions import lit

def with_greeting(df):
    return df.withColumn("greeting", lit("hi"))

def with_something(df, something):
    return df.withColumn("something", lit(something))

data = [("jose", 1), ("li", 2), ("luisa", 3)]
source_df = spark.createDataFrame(data, ["name", "age"])

actual_df = source_df\
    .transform(lambda df: with_greeting(df))\
    .transform(lambda df: with_something(df, "crazy"))
```

The Spark Scala API has a built-in transform method that lets users chain DataFrame transformations more elegantly, [as described in this blog post](https://medium.com/@mrpowers/chaining-custom-dataframe-transformations-in-spark-a39e315f903c).

Here's an interface I'd prefer (this is what we do in Scala and I know this will need to be changed around for Python, but I'd like something like this):

```python
def with_greeting()(df):
    return df.withColumn("greeting", lit("hi"))

def with_something(something)(df):
    return df.withColumn("something", lit(something))

data = [("jose", 1), ("li", 2), ("luisa", 3)]
source_df = spark.createDataFrame(data, ["name", "age"])

actual_df = source_df\
    .transform(with_greeting())\ # the transform method magically knows that self should be passed into the second parameter list
    .transform(with_something("crazy"))
```

[Here is the code that needs to be changed](https://github.com/MrPowers/quinn/blob/master/quinn/extensions/dataframe_ext.py).

If we can figure out a better interface, we should consider making a pull request to the Spark source code.  I use the `transform` method every day when writing Spark/Scala code and think this is a major omission in the PySpark API.

If my ideal interface isn't possible is there anything that's better?!   I really don't like my current solution that requires `lambda`.

@pirate - help!

**Comment by pirate** [comment]
Try a closure:

```python
def with_greeting(df):
    return df.withColumn("greeting", lit("hi"))

def with_something(something):
    def partial(df):
        return df.withColumn("something", lit(something))

data = [("jose", 1), ("li", 2), ("luisa", 3)]
source_df = spark.createDataFrame(data, ["name", "age"])

actual_df = (source_df
    .transform(with_greeting)   # no lambda required
    .transform(with_something("crazy"))
```

In JS this looks like:
```javascript
const myFunc = (first_set_of_args) => (second_set_of_args) => {
    ...function body
}
```

**Comment by pirate** [comment]
`functools.partial` actually works well for this too, although I think the closure method is cleaner/easier to understand:

```python
from functools import partial


def with_greeting(df):
    return df.withColumn("greeting", lit("hi"))

def with_something(something, df):
    return df.withColumn("something", lit(something))

data = [("jose", 1), ("li", 2), ("luisa", 3)]
source_df = spark.createDataFrame(data, ["name", "age"])

actual_df = (source_df
    .transform(with_greeting)
    .transform(partial(with_something, "crazy"))
```

**Comment by MrPowers** [comment]
Thanks @pirate. 

I [updated the test suite](https://github.com/MrPowers/quinn/commit/283629acd2a5544e53ad55ebbf92c77174bef799) to demonstrate how `functools.partial` can be used.  I also changed the string `"luisa"` to `"liz"` based on a code review from @lizparody 😉 

I also updated [the blog post](https://medium.com/@mrpowers/chaining-custom-pyspark-transformations-4f38a8c7ae55) to include a `functools.partial` example.

Thanks!

**Comment by lizparody** [comment]
AAHAHHAHAHAHAHAHAHAHAHAHAHAHAH 😂 it was a joke!!!

**Comment by pirate** [comment]
Fyi @MrPowers, you don't need partial on the first transform func for the same reason that you don't need a lambda there:

`lambda x: func(x)` == `partial(func)` == `func`

```python
actual_df = (source_df)
    .transform(with_greeting)
    .transform(partial(with_jacket, "warm")))
```

**Comment by MrPowers** [comment]
Thanks @pirate - I updated the code and blog post accordingly.

Thanks for all the help here - I really appreciate the feedback.  Feel free to rip up my code or blog posts anytime!!!

**Comment by MrPowers** [comment]
@pirate - @capdevc showed me how to use cytoolz to run multiple custom DataFrame transformations with function composition.  Take a look at [this commit](https://github.com/MrPowers/quinn/commit/27e1fe7fc9d29624aa42593128b325ed497f5f83).

Thanks @capdevc!!!

**Comment by capdevc** [comment]
@MrPowers I really like cytoolz and use it alot, but it's  pretty heavy dependency to pull in for just the curry decorator. It's also available in [toolz,](https://github.com/pytoolz/toolz) which is the same as cytoolz minus the cython bits. Even better, you could just add your own curry decorator since it's just a wrapper around `functools.partial`.

**Comment by MrPowers** [comment]
Closing this now that DataFrame#transform has been included in PySpark.  Really appreciate everyone's help.
