### ISSUE TITLE
Add typing to public interfaces

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#61]
We should type the public interface, similar to mack: https://github.com/MrPowers/mack/blob/main/mack/__init__.py

We currently have this:

```python
def single_space(col):
    return F.trim(F.regexp_replace(col, " +", " "))
```

It should be this:

```python
def single_space(col: Column):
    return F.trim(F.regexp_replace(col, " +", " "))
```

**Comment by SemyonSinchenko** [comment]
I can do it.

**Comment by MrPowers** [comment]
@SemyonSinchenko - awesome, assigned the issue to you.
