### ISSUE TITLE
Possibly use `Ruff` instead of `flake8`

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#67]
@MrPowers Why you do not want to use `Ruff` instead of `flake8`? It is more modern way with the same functionality...
https://beta.ruff.rs/docs/

_Originally posted by @SemyonSinchenko in https://github.com/MrPowers/quinn/issues/58#issuecomment-1458517215_

**Comment by SemyonSinchenko** [comment]
Motivation:
- Ruff is significantly faster (it should save us free minutes of GH Actions)
- Ruff will replace all isort, flake and pylint by one dependency
- Ruff is configured in one place (`pyproject.toml`): `[tool.ruff]` instead of different files/sections

**Comment by MrPowers** [comment]
@SemyonSinchenko - Just looked at the Ruff README and it looks amazing.  I am definitely interested.  Anyone else from the community have thoughts?

**Comment by souvik-databricks** [comment]
@MrPowers Let's do it. I have heard Ruff is crazy fast and I just now checked the [github page of the project](https://github.com/charliermarsh/ruff) and looks like major open source projects like **_FastAPI, SciPy and Apache Airflow_** is also using it.
<img width="504" alt="image" src="https://user-images.githubusercontent.com/98817232/223741160-84562068-0fba-4da6-976a-1fbdd60331fa.png">

**Comment by MrPowers** [comment]
@SemyonSinchenko - would you like to add Ruff?  Feel free to send a PR!

**Comment by MrPowers** [comment]
Going to do the work here: https://github.com/MrPowers/quinn/issues/69
