### ISSUE TITLE
Document functions that have no documentation

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#68]
Some examples:

* `week_start_date`
* `week_end_date`
* `array_choice`
* `regexp_extract_all`

Need to look through all the public interface methods and make sure they're all documented.

**Comment by GuND0Wn151** [comment]
Hello, So, all the Functions which are not present in the readme file are to be documented?

**Comment by MrPowers** [comment]
@GuND0Wn151 - Yea, we need to add the `week_start_date` function to the README in the [Functions section](https://github.com/MrPowers/quinn#functions).  Would you like to take a shot.

**Comment by MrPowers** [comment]
Awesome, assigned the issue to you.

**Comment by GuND0Wn151** [comment]
Hey I guess the PR has been merged can you close this issue, Or is there anything left?

**Comment by SemyonSinchenko** [comment]
Issue was closed in #79
