### ISSUE TITLE
Using GH-Pages for hosting documentation of API

### ISSUE THREAD

**Issue by SemyonSinchenko** [MrPowers/quinn#71]
My suggestion is to use GH-Pages for API Docs (instead of README.md).

There are few options:
1. Use `mkdocs`: [deploying MKDocs to GHP](https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages)
2. Use `sphinx`: [GH Action to deploy Sphinx to GHP](https://github.com/marketplace/actions/sphinx-to-github-pages)

Anyway there will be a day when amount of public functions and helpers will be so big that it is not fin into a single README page...

P.S. Also it will solve the problem with outdated documentation because we will use functions/methods signatures and docstrings to update documentation as a CI/CD step after push into main branch.

**Comment by MrPowers** [comment]
@SemyonSinchenko - Yes, let's try mkdocs and GH-Pages to host the docs for this project.  Would you like to submit a PR?

I will still want to highlight the best and most used quinn functions in the README, even after we have an official docs page setup.  I understand that's a bigger maintenance burden, but worth it for potential users to immediately see the value of the project.

Let me know if you're alright taking a stab and I'll assign you to the issue.  Thanks!

**Comment by SemyonSinchenko** [comment]
> Would you like to submit a PR?

I can do it in my fork but I guess that it will require some efforts from your side too (cause GH Pages pushes HTMLs into special branch). But in short words: I can do it.
