### ISSUE TITLE
Document print_schema_as_code in README

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#72]
Document print_schema_as_code in the README

Also make a post on LinkedIn to show users about this functionality.

**Comment by michel-public** [comment]
I would like to work on this one. Experienced with Python and I understand Spark, but my git/github knowledge is limited.

**Comment by MrPowers** [comment]
Sounds good @michel-public, just assigned this issue to you.  Thanks!

**Comment by MrPowers** [comment]
@michel-public - please let us know when the PR Is ready for review, thank you!

**Comment by kavinrites** [comment]
@MrPowers 
came here from the below reditt thread.
https://www.reddit.com/r/dataengineering/comments/ms33t0/open_source_contributions_for_a_data_engineer/
It looks like this can be closed as I see print_schema_as_code is available in README now

**Comment by SemyonSinchenko** [comment]
@kavinrites Thank you for pointing our attention to it. You are absolutely right, it is Done.
