### ISSUE TITLE
[Feature request] Functionality for working with FileSystem with PySpark

### ISSUE THREAD

**Issue by SemyonSinchenko** [MrPowers/quinn#77]
By default Spark does not provide functionality to read and write files on HDFS/S3/LocalFS. In Scala one can do it via `org.apache.hadoop.fs.FileSystem` but in PySpark it is not so easy to implement. I want to have a class like `HadoopFileSystem` or `SparkWriter` / `SparkReader` which provides top level `read_bytes` / `write_bytes` / `glob` / `mkdir` / `touch` functionality and uses `org.apache.hadoop.fs.FileSystem` via `py4j` under the hood. Something like `dbutils.fs` from Databricks but open source and with zero-dependencies.

I see it as a class with static init methods like `fs = quin.fs.FileSystem.fromPath("s3a://...", session=spark)` which under the hood uses `org.apache.hadoop.fs.Path.toUri()` and `org.apache.hadoop.fs.FileSystem.get(uri, configuration)` to choose the right implementation of `FileSystem` (HDFS, S3 or Local) automatically. It is important especially in unit testing because allows user do not patch class but just use local FS for tests.

I know how to implement it (I did the same thing with scala already and for PySpark I should just wrap all the scala calls into Py4j). The question is mostly about design and which additional methods should I implement? Maybe some additional things like `cp`, `mv`, `createIfNotExists` and so fourth and so on? Maybe also some top level syntax sugar like `writePickle`, etc?

Also with such a class we can easily implement functionality which write and read Excel files from FileSystem with PySpark (but under the hood there will be Pandas and it will work only for small files).

**Comment by MrPowers** [comment]
@SemyonSinchenko - great questions.  Here are a few libraries @brayanjuls and I are working on to help expose some of those APIs:

* [brayanjuls/hio](https://github.com/brayanjuls/hio): HDFS filesystem and object store helper methods (Scala)
* [brayanjuls/diane](https://github.com/brayanjuls/diane): Hive helper functions for apache spark users (Scala)
* [MrPowers/eren](https://github.com/mrpowers/eren): PySpark Hive helper methods (Python)

Sounds like you have some good ideas on how to make those projects better.  We may want to use py4j to expose Python bindings to brayanjuls/hio.  I created an issue: https://github.com/brayanjuls/hio/issues/1

Would love you help on [eren](https://github.com/MrPowers/eren/issues) BTW.  Really think the PySpark community needs a better way to interact with Hive.

**Comment by SemyonSinchenko** [comment]
> We may want to use py4j to expose Python bindings to brayanjuls/hio

It sounds great but ... it will require to have `hio` JAR in Spark runtime which can be problematic (all the prod clusters which I saw did not have an access to Maven central and adding some jar is a real problem). And I'm afraid that it will make installation process like a hell. My idea is to have a zero-dependency way in some lightweight library (like this one).

But we can to it inside `eren`!

**Comment by SemyonSinchenko** [comment]
I think we can close this one because this functionality is already in `Eren`.
