### ISSUE TITLE
Python 2.7 Compatibility

### ISSUE THREAD

**Issue by ewellinger** [MrPowers/quinn#8]
Hey @MrPowers,

First off this package looks pretty sweet and something we could definitely work into our analytics pipeline, so nicely done!  Unfortunately we have some system requirements that are holding us back in the python 2.7 realm (mostly the cloud infrastructure and a few pesky python 2 only packages) and was wondering what your opinion would be on adapting this code to also work in python 2?  

To be clear, I would be doing this work and getting a PR in for adding that functionality, mostly wondering if there are any outstanding difficulties that exist off the top of your head.  Let me know as I'd love to get this incorporated into our production processes!

Best,
Erich

**Comment by ewellinger** [comment]
As far as I can tell it only took a few formatting changes (e.g. changing `f"{var}"` to `"{var}".format(var=var)`) to get all the tests working.  I'll update the required libraries and open a PR later today.

**Comment by MrPowers** [comment]
@ewellinger - Cool, send me a pull request and I'll be happy to merge it in 😄

**Comment by ewellinger** [comment]
Please see [this PR](https://github.com/MrPowers/quinn/pull/9).  Thanks!

**Comment by MrPowers** [comment]
@ewellinger - Can you please confirm everything is working in Python 2.7 in production?  I'll close this issue once I get your confirmation.

**Comment by ewellinger** [comment]
Hmm, looks like something isn't quite right with the publishing to pypi.  I tried to incorporate it into our Docker image to verify everything is working in production and running into an error when I try installing it from pip.
This is the error I'm getting:
```
Collecting quinn
  Could not find a version that satisfies the requirement quinn (from versions: )
No matching distribution found for quinn
```
I set it so the package itself requires python 2.7 and above but I'm thinking pypi needs it to be marked as working for both?  I did see this in the section of the pypi tutorial on publishing packages with the [`python_requires` argument](https://packaging.python.org/tutorials/distributing-packages/#python-requires):

> Note Support for this feature is relatively recent. Your project’s source distributions and wheels (see Packaging your Project) must be built using at least version 24.2.0 of setuptools in order for the python_requires argument to be recognized and the appropriate metadata generated.

In the meantime I'll try just zipping up the repo and incorporate it into an example job just to make sure the code itself works as expected.

Also, should we be including a license along with this?

**Comment by ewellinger** [comment]
I think uploading it as an egg rather than a version specific wheel might fix the issue?  That or you can upload two wheels, one for each version.

**Comment by ewellinger** [comment]
I was able to follow the instructions in the RELEASE.md file for building the wheel for python 2 but it's unsurprisingly not allowing me to upload that to PyPi.  @MrPowers, could you either upload a python 2 wheel or allow me (user ewellinger on pypi) to upload to the project?
Thanks!

**Comment by MrPowers** [comment]
@ewellinger - I updated the Python 2 wheel file [here](https://pypi.python.org/pypi/quinn/0.2.1).

The filename is `quinn-0.2.1-py2-none-any.whl`.  Can you please let me know if that works for you?  Thanks!

**Comment by ewellinger** [comment]
Yes, it worked (as far as pip installing it successfully)!  I'm going to add it to our docker image and see if it works with our CI testing.  If that all works then I think we'll be good to close out this issue.

**Comment by MrPowers** [comment]
Awesome @ewellinger, keep me posted 😄

**Comment by ewellinger** [comment]
Sorry for the long delay in responding but I have tested this in our production setting and it looks good!  Thanks
