### ISSUE TITLE
Run tests for different PySpark versions

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#82]
We should update the GitHub actions to run the tests for both PySpark 2.x and PySpark 3.x.

I am only running the tests with PySpark 3.x locally when I am merging changing.  We should also run tests with PySpark 2.x to make sure we're not making any breaking changes.

**Comment by Breaka84** [comment]
Hi @MrPowers,

I wanted to contribute for this project for a long time now so I grabbed this issue. I use quite the same functionality for my project, so it looked straightforward. It was not... :laughing:  Spark 2.x :roll_eyes: 
However, I got it working in the end. Here's the [PR](https://github.com/MrPowers/quinn/pull/98)!

**Comment by jeffbrennan** [comment]
@MrPowers can this be closed?
