### ISSUE TITLE
Add a function to compute the number of business days between two dates

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/quinn#84]
See [this comment](https://github.com/MrPowers/quinn/issues/83#issuecomment-1466894207) and some of the other comments that follow.

The function should be in [functions.py](https://github.com/MrPowers/quinn/blob/main/quinn/functions.py) and be called something like `business_days_between` or something (consistent with this [this answer](https://stackoverflow.com/a/4027849)).

**Comment by fpvmorais** [comment]
Here's a possible solution to calculate:

`CREATE FUNCTION IF NOT EXISTS udf_workdays(StartDate date,
                                           EndDate date,
                                           Holidays array<date> array())
RETURNS int
RETURN
(
    REDUCE(
      ARRAY_EXCEPT(SEQUENCE(StartDate, EndDate),Holidays)
      0,
      (acc, x) -> acc + IF(DATE_FORMAT(x, 'E') IN ('Sat', 'Sun'), 0, 1))
);`

This UDF can accept an optional list of holidays to exclude besides the weekend days

**Comment by robertkossendey** [comment]
Thank you for the contribution! But I think we should make it work without an UDF, so that Spark can optimize the query

**Comment by puneetsharma04** [comment]
@MrPowers : I would like to work on this issue , can you assign this issue to me?

**Comment by MrPowers** [comment]
This was added!
